---
- name: docker build and push
  hosts: kvm1
  become: yes

  tasks:
    - name: Build an image and push it to a repo
      docker_image:
        path: ./main
        name: rudclthe/testimg
        tag: {{TAG}}
        push: yes
